# This file contains 51 country codes (pn codes) for Google Trends as of 26-09-2024.
# The list includes codes that were updated and verified directly from Google's data on this date.
# Please ensure that any reference or usage of these pn codes in other projects or publications includes proper attribution.

# Country codes (Google Trends 'pn' parameter for each country)
country_codes = {
    "TURKIYE": "p24",
    "ARGENTINA": "p30",
    "AUSTRALIA": "p8",
    "AUSTRIA": "p44",
    "BELGIUM": "p41",
    "BRAZIL": "p18",
    "CANADA": "p13",
    "CHILE": "p38",
    "COLOMBIA": "p32",
    "CZECHIA": "p43",
    "DENMARK": "p49",
    "EGYPT": "p29",
    "FINLAND": "p50",
    "FRANCE": "p16",
    "GERMANY": "p15",
    "GREECE": "p48",
    "GREENLAND": "p0",
    "HONG_KONG": "p10",
    "HUNGARY": "p45",
    "INDIA": "p3",
    "INDONESIA": "p19",
    "IRELAND": "p54",
    "ISRAEL": "p6",
    "ITALY": "p27",
    "JAPAN": "p4",
    "KENYA": "p37",
    "MALAYSIA": "p34",
    "MEXICO": "p21",
    "NETHERLANDS": "p17",
    "NEW_ZEALAND": "p53",
    "NIGERIA": "p52",
    "NORWAY": "p51",
    "PERU": "p55",
    "PHILIPPINES": "p25",
    "POLAND": "p31",
    "PORTUGAL": "p47",
    "ROMANIA": "p39",
    "RUSSIA": "p14",
    "SAUDI_ARABIA": "p36",
    "SINGAPORE": "p5",
    "SOUTH_AFRICA": "p40",
    "SOUTH_KOREA": "p23",
    "SPAIN": "p56",
    "SWEDEN": "p42",
    "SWITZERLAND": "p46",
    "TAIWAN": "p12",
    "THAILAND": "p33",
    "UKRAINE": "p35",
    "UNITED_KINGDOM": "p9",
    "UNITED_STATES": "p1",
    "VIETNAM": "p28"
}
